config/routes.rb
TalkingSlate::Application.routes.draw do
  resources :conferences


  resources :profiles

bigbluebutton_routes :default
  

  authenticated :user do
    root :to => 'profiles#new'
  end
  
  devise_for :users
  resources :users
end

app/models/conference.rb
class Conference < ActiveRecord::Base
  attr_accessible :alternate_contact_details, :category, :class_end, :class_start, :cost, :payment_options, :recurrence, :slots_avialable, :subject, :upload_ad, :upload_demo_video
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :address, :certification, :college, :contact_no, :first_name, :higher_education, :interested_in_learning, :last_name, :profile_pic, :school, :user_id, :would_like_to_teach, :about_video, :about_video_html

  AutoHtml.add_filter(:image) do |text|
    text.gsub(/http:\/\/.+\.(jpg|jpeg|bmp|gif|png)(\?\S+)?/i) do |match|
      %|<img src="#{match}" alt=""/>|
    end
  end
  auto_html_for :about_video do
    image
    youtube(:width => 170, :height => 100)
    link :target => "_blank", :rel => "nofollow"
    simple_format
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authenticate_user!
  protect_from_forgery
  
  layout :layout_by_resource
  
  def layout_by_resource
    if user_signed_in?
      "home_page"
    else
      "landing_page"
    end
  end

end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
  # GET /conferences
  # GET /conferences.json
  def index
    @conferences = Conference.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @conferences }
    end
  end

  # GET /conferences/1
  # GET /conferences/1.json
  def show
    @conference = Conference.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @conference }
    end
  end

  # GET /conferences/new
  # GET /conferences/new.json
  def new
    @conference = Conference.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @conference }
    end
  end

  # GET /conferences/1/edit
  def edit
    @conference = Conference.find(params[:id])
  end

  # POST /conferences
  # POST /conferences.json
  def create
    @conference = Conference.new(params[:conference])

    respond_to do |format|
      if @conference.save
        format.html { redirect_to @conference, notice: 'Conference was successfully created.' }
        format.json { render json: @conference, status: :created, location: @conference }
      else
        format.html { render action: "new" }
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /conferences/1
  # PUT /conferences/1.json
  def update
    @conference = Conference.find(params[:id])

    respond_to do |format|
      if @conference.update_attributes(params[:conference])
        format.html { redirect_to @conference, notice: 'Conference was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conferences/1
  # DELETE /conferences/1.json
  def destroy
    @conference = Conference.find(params[:id])
    @conference.destroy

    respond_to do |format|
      format.html { redirect_to conferences_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @profiles }
    end
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @profile = Profile.find(params[:id])
    @conferences = Conference.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/new
  # GET /profiles/new.json
  def new
    @profile = Profile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/1/edit
  def edit
    @profile = Profile.find(params[:id])
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(params[:profile])

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render json: @profile, status: :created, location: @profile }
      else
        format.html { render action: "new" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /profiles/1
  # PUT /profiles/1.json
  def update
    @profile = Profile.find(params[:id])

    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conferences_helper.rb
module ConferencesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/bigbluebutton/rooms/_form.html.erb
<% if @room.new_record? %>
  <% url = bigbluebutton_rooms_path %>
<% else %>
  <% url = bigbluebutton_room_path(@room) %>
<% end %>

<%= form_for @room, :url => url do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %>:</h2>
      <ul>
      <% @room.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :server_id %><br />
    <%= f.text_field :server_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :meetingid %><br />
    <%= f.text_field :meetingid %>
  </div>
  <div class="field">
    <%= f.label :randomize_meetingid %><br />
    <%= f.check_box :randomize_meetingid %>
  </div>
  <div class="field">
    <%= f.label :private %><br />
    <%= f.check_box :private %>
  </div>
  <div class="field">
    <%= f.label :attendee_password %><br />
    <%= f.password_field :attendee_password %>
  </div>
  <div class="field">
    <%= f.label :moderator_password %><br />
    <%= f.password_field :moderator_password %>
  </div>
  <div class="field">
    <%= f.label :welcome_msg %><br />
    <%= f.text_field :welcome_msg %>
  </div>
  <div class="field">
    <%= f.label :logout_url %><br />
    <%= f.text_field :logout_url %>
  </div>
  <div class="field">
    <%= f.label :dial_number %><br />
    <%= f.text_field :dial_number %>
  </div>
  <div class="field">
    <%= f.label :voice_bridge %><br />
    <%= f.text_field :voice_bridge %>
  </div>
  <div class="field">
    <%= f.label :max_participants %><br />
    <%= f.text_field :max_participants %>
  </div>
  <div class="field">
    <%= f.label :external %><br />
    <%= f.check_box :external %>
  </div>
  <div class="field">
    <%= f.label :param %><br />
    <%= f.text_field :param %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bigbluebutton/rooms/_rooms.html.erb
<div id="bbbrails_rooms_links">
  <%= link_to('View servers list', bigbluebutton_servers_path) %><br/>
  <%= link_to('New room', new_bigbluebutton_room_path) %>
</div>

<ul id="bbbrails_rooms_list">
  <% @rooms.each do |room| %>
    <li>
      <div class="field">
        <label><%= BigbluebuttonRoom.human_attribute_name(:server_id) %></label> <%= room.server_id %>
        <%= link_to('(view server)', bigbluebutton_server_path(room.server)) unless room.server.nil? %>
      </div>
      <div class="field"><label><%= BigbluebuttonRoom.human_attribute_name(:meetingid) %></label> <%= room.meetingid %></div>
      <div class="field"><label><%= BigbluebuttonRoom.human_attribute_name(:randomize_meetingid) %></label> <%= room.randomize_meetingid %></div>
      <div class="field"><label><%= BigbluebuttonRoom.human_attribute_name(:name) %></label> <%= room.name %></div>
      <div class="field"><label><%= BigbluebuttonRoom.human_attribute_name(:private) %></label> <%= room.private %></div>
      <div class="field"><label><%= BigbluebuttonRoom.human_attribute_name(:attendee_password) %></label> <%= room.attendee_password %></div>
      <div class="field"><label><%= BigbluebuttonRoom.human_attribute_name(:moderator_password) %></label> <%= room.moderator_password %></div>
      <div class="field"><label><%= BigbluebuttonRoom.human_attribute_name(:welcome_msg) %></label> <%= room.welcome_msg %></div>
      <div class="field"><label><%= BigbluebuttonRoom.human_attribute_name(:logout_url) %></label> <%= room.logout_url %></div>
      <div class="field"><label><%= BigbluebuttonRoom.human_attribute_name(:dial_number) %></label> <%= room.dial_number %></div>
      <div class="field"><label><%= BigbluebuttonRoom.human_attribute_name(:voice_bridge) %></label> <%= room.voice_bridge %></div>
      <div class="field"><label><%= BigbluebuttonRoom.human_attribute_name(:max_participants) %></label> <%= room.max_participants %></div>
      <div class="field"><label><%= BigbluebuttonRoom.human_attribute_name(:external) %></label> <%= room.external %></div>
      <div class="field"><label><%= BigbluebuttonRoom.human_attribute_name(:param) %></label> <%= room.param %></div>
      <div class="field"><label>Access</label>
        <%= link_to 'Show', bigbluebutton_room_path(room) %> |
        <%= link_to 'Join', join_bigbluebutton_room_path(room) %> |
        <%= link_to 'Invite', invite_bigbluebutton_room_path(room) %> |
        <%= link_to 'Mobile Join', join_mobile_bigbluebutton_room_path(room) %> |
        <%= link_to 'Edit', edit_bigbluebutton_room_path(room) %> |
        <%= link_to 'End', end_bigbluebutton_room_path(room), :confirm => 'Are you sure?' %> |
        <%= link_to 'Destroy', bigbluebutton_room_path(room), :confirm => 'Are you sure?', :method => :delete %>
      </div>
    </li>
  <% end %>
</ul>

app/views/bigbluebutton/rooms/edit.html.erb
<h1>Edit <%= BigbluebuttonRoom.model_name.human %>:</h1>
<%= render 'form' %>

<%= link_to 'Show', bigbluebutton_room_path(@room) %> |
<%= link_to 'Back', bigbluebutton_rooms_path %>

app/views/bigbluebutton/rooms/external.html.erb
<h1>Join the meeting <%= @room.name %></h1>

<div id="error_explanation"><%= flash[:error] %></div>

<p>This meeting was created from another application.<br/>You must provide a name and a password to join:</p>

<%= form_tag external_bigbluebutton_rooms_path do %>
  <%= hidden_field_tag "server_id", params[:server_id] %>
  <%= hidden_field_tag "meeting", params[:meeting] %>

  <div class="field">
    <label for="user_name">Name:</label><br />
    <% if bigbluebutton_user.nil? %>
      <%= text_field_tag "user[name]", "" %>
    <% else %>
      <%= text_field_tag "user[name]", bigbluebutton_user.name %>
    <% end %>
  </div>
  <div class="field">
    <label for="user_password">Password:</label><br />
    <%= password_field_tag "user[password]", "" %>
  </div>

  <%= submit_tag "Submit" %>
<% end %>

app/views/bigbluebutton/rooms/index.html.erb
<h1>Listing rooms:</h1>
<%= render 'rooms' %>

app/views/bigbluebutton/rooms/invite.html.erb
<script type="text/javascript">

function ajax_request() {
  $.ajax({
    url: "<%= running_bigbluebutton_room_url(@room, :format => 'json') %>",
    dataType: 'json',
    error: function(xhr_data) {
      $("#meeting_status").html("<request error>.");
      setTimeout(function() { ajax_request(); }, 10000);
    },
    success: function(xhr_data) {
      if (xhr_data.running == 'false') {
        $("#meeting_status").html("not running.");
      } else {
        $("#meeting_status").html("running!");
      }
      setTimeout(function() { ajax_request(); }, 10000);
    },
    contentType: 'application/json'
  });
}

$(document).ready(function(){
  ajax_request();
});

</script>

<h1>Invite to the meeting <%= @room.name %></h1>

<%# bbb_rails_error_explanation %>

<p>Meeting status: <span id="meeting_status">-</span> (<a href="javascript:ajax_request();">refresh</a>)</p>

<div class="bbbrails_invite_device_type">
  <% if params[:mobile] %>
    In this page you can join the conference from a <b>mobile device</b>.
    To join from a desktop <%= link_to "click here", invite_bigbluebutton_room_path(@room) %>.
  <% else %>
    In this page you can join the conference from a <b>desktop</b>.
    To join from a mobile device <%= link_to "click here", invite_bigbluebutton_room_path(@room, :mobile => true) %>.
  <% end %>
</div>

<p><%= @room.name %> requires a name and/or password to join:</p>
<%= form_tag join_bigbluebutton_room_path(@room, :mobile => params[:mobile]) do %>

  <div class="field">
    <label for="user_name">Name:</label><br />
    <% if bigbluebutton_user.nil? %>
      <%= text_field_tag "user[name]", "" %>
    <% else %>
      <%= text_field_tag "user[name]", bigbluebutton_user.name, :readonly => true %>
    <% end %>
  </div>
  <div class="field">
    <label for="user_password">Password:</label><br />
    <% if @user_role == :attendee %>
      <%= password_field_tag "user[password]", @room.attendee_password, :readonly => true %>
    <% elsif @user_role == :moderator %>
      <%= password_field_tag "user[password]", @room.moderator_password, :readonly => true %>
    <% else %>
      <%= password_field_tag "user[password]", "" %>
    <% end %>
  </div>

  <%= submit_tag "Submit" %>
<% end %>

app/views/bigbluebutton/rooms/join.html.erb
<script type="text/javascript">

function ajax_request() {
  $.ajax({
    url: "<%= running_bigbluebutton_room_url(@room, :format => 'json') %>",
    dataType: 'json',
    error: function(xhr_data) {
      //
    },
    success: function(xhr_data) {
      if (xhr_data.running == 'true') {
        window.location.reload();
      }
      setTimeout(function() { ajax_request(); }, 3000);
    },
    contentType: 'application/json'
  });
}

$(document).ready(function(){
  ajax_request();
});

</script>

<h1>Meeting <%= @room.name %></h1>

<%= image_tag "loading.gif" %>
<p>The meeting has not started yet, you must wait for the moderator to join.</p>
<p>Your browser will automatically refresh and join the meeting when it starts.</p>

app/views/bigbluebutton/rooms/join_mobile.html.erb
<h1>Mobile access to <%= @room.name %></h1>

<div style="text-align:center; width:250px;">
  <a href="<%= @join_url %>"><b>Click here</b><br/>to join from a mobile device</a><br><br/>
  <span>Or scan the code below:</span><br/>
  <img src="<%= qrcode_url(@qrcode_url) %>" style="float:left; border:1px solid #ccc;"/>
</div>

app/views/bigbluebutton/rooms/new.html.erb
<h1>New <%= BigbluebuttonRoom.model_name.human %>:</h1>

<%= render 'form' %>

<%= link_to 'Back', bigbluebutton_rooms_path %>

app/views/bigbluebutton/servers/_activity_list.html.erb
<% server.meetings.each do |room| %>
  <div class="bbbrails_meeting_description">
    <div class="title_bar">
      <% unless room.new_record? %>
        <div class="button_bar">
          <%= link_to 'Show', bigbluebutton_room_path(room) %>
          <%= link_to 'Edit', edit_bigbluebutton_room_path(room) %>
          <%= link_to 'Destroy', bigbluebutton_room_path(room), :confirm => 'Are you sure?', :method => :delete %>
        </div>
        <div class="button_bar">
          <%= link_to 'Join', join_bigbluebutton_room_path(room) %>
          <%= link_to 'Mobile Join', join_mobile_bigbluebutton_room_path(room) %>
          <%= link_to 'End', end_bigbluebutton_room_path(room), :confirm => 'Are you sure?' %>
        </div>
      <% end %>
      <b><%= room.name %></b> (ID: <%= room.meetingid %>) -
      <% if room.is_running? %>
        <span class="running">Running!</span>
      <% else %>
        <span class="not_running">Not running</span>
      <% end %>
    </div>
    <% unless room.start_time.nil? %>
      Started at: <%= room.start_time.strftime("%F, %R UTC%z") %><br/>
    <% end %>
    <% unless room.end_time.nil? %>
      Ended at: <%= room.end_time.strftime("%F, %R UTC%z") %> (forcibly ended: <%= room.has_been_forcibly_ended %>)
    <% end %>
    <% unless room.attendees.count == 0 %>
      Participants (<%= room.participant_count %> total, <%= room.moderator_count %> moderators):
      <div class="bbbrails_meeting_attendees">
        <div class="header">
          <div class="field">Role</div>
          <div class="field">ID</div>
          <div class="field">Name</div>
        </div>
        <% room.attendees.each do |attendee| %>
          <div class="row">
            <div class="field"><%= attendee.role %></div>
            <div class="field"><%= attendee.user_id %></div>
            <div class="field"><%= attendee.full_name %></div>
          </div>
        <% end %>
      </div>
    <% end %>
    <div style="clear:both;"></div>
  </div>
<% end %>

app/views/conferences/edit.html.erb
<h1>Editing conference</h1>

<%= render 'form' %>

<%= link_to 'Show', @conference %> |
<%= link_to 'Back', conferences_path %>

app/views/conferences/index.html.erb
<h1>Listing conferences</h1>

<table>
  <tr>
    <th>Subject</th>
    <th>Category</th>
    <th>Class start</th>
    <th>Class end</th>
    <th>Slots avialable</th>
    <th>Recurrence</th>
    <th>Cost</th>
    <th>Payment options</th>
    <th>Alternate contact details</th>
    <th>Upload demo video</th>
    <th>Upload ad</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @conferences.each do |conference| %>
  <tr>
    <td><%= conference.subject %></td>
    <td><%= conference.category %></td>
    <td><%= conference.class_start %></td>
    <td><%= conference.class_end %></td>
    <td><%= conference.slots_avialable %></td>
    <td><%= conference.recurrence %></td>
    <td><%= conference.cost %></td>
    <td><%= conference.payment_options %></td>
    <td><%= conference.alternate_contact_details %></td>
    <td><%= conference.upload_demo_video %></td>
    <td><%= conference.upload_ad %></td>
    <td><%= link_to 'Show', conference %></td>
    <td><%= link_to 'Edit', edit_conference_path(conference) %></td>
    <td><%= link_to 'Destroy', conference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Conference', new_conference_path %>

app/views/conferences/new.html.erb
<h1>New conference</h1>

<%= render 'form' %>

<%= link_to 'Back', conferences_path %>

app/views/conferences/show.html.erb
<p id="notice"><%= notice %></p>
<div class="large-6 small-centered columns">
  <h1> Create session</h1>
</div>
<div class="row">
  <div class="large-8 columns">
    <div class="large-6 columns">
      Subject:
    </div>
    <div class="large-6 columns">
      <%= @conference.subject %>
    </div>
    <div class="large-6 columns">
      Category:
    </div>
    <div class="large-6 columns">
      <%= @conference.category %>
    </div>
    <div class="large-6 columns">
      <div class="titleconf">
        Class room
      </div>
      <div class="large-6 columns">
        Start Date:
      </div>
      <div class="large-6 columns">
        <%= @conference.class_start %>
      </div>
      <div class="large-6 columns">
        Start Time:
      </div>
      <div class="large-6 columns">
        <%= @conference.class_start %>
      </div>
      <div class="large-12 columns">
        Recurrance:
      </div>

    </div>
    <div class="large-6 columns">
      <div class="titleconf">
        Telecaster
      </div>
      <div class="large-6 columns">
        End Date:
      </div>
      <div class="large-6 columns">
        <%= @conference.class_end %>
      </div>
      <div class="large-6 columns">
        End Time:
      </div>
      <div class="large-6 columns">
        <%= @conference.class_end %>
      </div>
      <div class="large-12 columns">
        <%= @conference.recurrence %>
      </div>
    </div>
    <div class="large-6 columns">
      Slots Available
    </div>
    <div class="large-6 columns">
      <%= @conference.slots_avialable %>
    </div>
    <div class="large-6 columns">
      Cost
    </div>
    <div class="large-6 columns">
      <%= @conference.cost %>
    </div>
    <div class="large-6 columns">
      <b>Payment Options</b>
    </div>
    <div class="large-6 columns">
      <%= @conference.payment_options %>
    </div>

    <div class="large-6 columns">
      <b>Alternate Contact Details</b>
    </div>
    <div class="large-6 columns">
      <%= @conference.alternate_contact_details %>
    </div>
  </div>
  <div class="large-4 columns">

  </div>
</div>

<!--
<p>
  <b>Class start:</b>
  <%= @conference.class_start %>
</p>

<p>
  <b>Class end:</b>
  <%= @conference.class_end %>
</p>

<p>
  <b>Slots available:</b>
  <%# @conference.slots_available %>
</p>

<p>
  <b>Recurrence:</b>
  <%= @conference.recurrence %>
</p>

<p>
  <b>Cost:</b>
  <%= @conference.cost %>
</p>

<p>
  <b>Payment options:</b>
  <%= @conference.payment_options %>
</p>

<p>
  <b>Alternate contact details:</b>
  <%= @conference.alternate_contact_details %>
</p>

<p>
  <b>Upload demo video:</b>
  <%= @conference.upload_demo_video %>
</p>

<p>
  <b>Upload ad:</b>
  <%= @conference.upload_ad %>
</p>
--!>

<%= link_to 'Start session', new_bigbluebutton_room_path, :class => "button small start_right" %> <br />

<%= link_to 'Edit', edit_conference_path(@conference) %> |
<%= link_to 'Back', conferences_path %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <tr>
    <th>Profile pic</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Address</th>
    <th>Contact no</th>
    <th>School</th>
    <th>College</th>
    <th>about_video</th>
    <th>Higher education</th>
    <th>Certification</th>
    <th>Interested in learning</th>
    <th>Would like to teach</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @profiles.each do |profile| %>
  <tr>
    <td><%= profile.profile_pic %></td>
    <td><%= profile.first_name %></td>
    <td><%= profile.last_name %></td>
    <td><%= profile.address %></td>
    <td><%= profile.contact_no %></td>
    <td><%= profile.school %></td>
    <td><%= profile.college %></td>
    <td><%= profile.about_video_html %>
    <td><%= profile.higher_education %></td>
    <td><%= profile.certification %></td>
    <td><%= profile.interested_in_learning %></td>
    <td><%= profile.would_like_to_teach %></td>
    <td><%= profile.user_id %></td>
    <td><%= link_to 'Show', profile %></td>
    <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
    <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<div class = "row">
  <p id="notice"><%= notice %></p>
  <div class="large-3 columns">
        <%# image_tag @profile.profile_pic_url(:thumb).to_s %>
            <p>
              <b> <%= @profile.first_name %></b>
            </p>
         <!--   <p>
              <b>Age:</b>
              <%# @profile.current_user.name %>
            </p>-->
   <div id="generalsettings">
      Account Settings <br/> User History <br/> Sessions History <br/> Upcoming Sessions<br /><br />
      <b>School bag</b>
      <% @conferences.each do |c|%>

      <p>
        <b><%= link_to c.subject, c %><b><br />
          <%= c.category %>&nbsp<%= c.class_start %>
        </p> <br />
        <% end %>
      </div>
      <p>
        Recommended Courses
      </p>
      <p>
        People/Institute Following
      </p>
   </div>
 
 <div class="large-7 columns" id="middlecolumn">
    <input type="search" placeholder="Search">
    <div class="large-12 columns" id="email">
      <div class="espan">
        <p>Email/Messages</p>
      </div>
    </div>

    <div class="large-12 columns" id="vidad">
      <div class="large-6 columns" id="dvideofc">
        <%= @profile.about_video_html %>
      </div>
      <div class="large-6 columns" id="ads">
        Ad
      </div>
    </div>
    <div class="large-12 columns">
      <div class="large-6 left columns" id="btn">
        <%= link_to 'Go to Class Room', new_bigbluebutton_room_path, :class => 'button radius medium' %>
      </div>
      <div class="large-6 right columns" id="btn">
        <%= link_to 'Create Session', new_conference_path, :class => 'button radius medium' %>
      </div>
    </div>
    
  </div>

  <div class="large-2 columns" id="rightcolumn">
    <% if @conferences.count >= 1 %>

    <a href="/conferences/show">
      <div class="button radius small disabled alert">  <%= link_to 'Sessions on', conferences_path %></div>
    </a>

    <% else %>

    <div class="button radius small alert">  Sessions off </div>
    <% end %>
  </div>
 
</div>

  <div class ="row" id="footer">
    <div class="large-8 large-centered columns">
    </div>
    <div class="large-4 columns">
      <p>Feedback</p>
      <p>Online chat help</p>
    </div>
  </div>